In [1]:
import numpy as np

# Arange()

In [2]:
arr1 = np.arange(1,6)
print(arr1)

[1 2 3 4 5]


In [3]:
arr2 = np.arange(1,10,2) # np.arange(start, stop, step)
print(arr2)

[1 3 5 7 9]


In [4]:
arr3 = np.arange(10,0,-2)
print(arr3)

[10  8  6  4  2]


# Zeros(), Ones() and Full()

In [5]:
z1 = np.zeros(4) # 1-d array
z2 = np.zeros((2,3)) # 2d array (2-row 3-column)
print(z1, end="\n\n")
print(z2)

[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
o1 = np.ones(6) # 1d array
print(o1, end='\n\n')
o2 = np.ones((5,5)) # 2d array (5-row 5-column)

print(o2)

[1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
f1 = np.full(5,2) # 1d array
print(f1)
print()
print(np.full((4,3),7)) # 2d array (4-row 3-column)

[2 2 2 2 2]

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


# random.randint()

In [8]:
r1 = np.random.randint(2,10,4) 
    #np.random.randint(start, end, number_of_values)
print(r1)

[3 8 3 5]


In [9]:
r2 = np.random.randint(5,50,10)
print(r2)

[ 6 32 48 23 24 33 40 46 30 48]


# eye()

In [10]:
# creating 2x2 identity matrix
identity_matrix1 = np.eye(2)
print(identity_matrix1)

[[1. 0.]
 [0. 1.]]


In [12]:
# creating 5x5 identity matrix
identity_matrix2 = np.eye(5)
print(identity_matrix2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# linspace()

In [15]:
linear_space = np.linspace(0,10,5)
print(linear_space)

[ 0.   2.5  5.   7.5 10. ]


In [27]:
l2 = np.linspace(10, 100, 10)
l2

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])