In [1]:
import numpy as np

# .shape

In [2]:
arr1 = np.arange(10, 50, 5)
print(arr1)
arr1.shape

[10 15 20 25 30 35 40 45]


(8,)

In [3]:
arr2 = np.linspace(10, 50, 5)
arr2.shape

(5,)

In [4]:
arr3 = np.full((2,3),5)
arr3.shape

(2, 3)

# .size

In [5]:
arr1 = np.arange(10, 50, 5)
print(arr1)
arr1.size

[10 15 20 25 30 35 40 45]


8

In [6]:
arr2 = np.eye(5)
arr2.size

25

In [7]:
arr3 = np.full((2,3),5)
arr3.size

6

# .ndim

In [8]:
arr1 = np.arange(10, 50, 5)
print(arr1)
arr1.ndim

[10 15 20 25 30 35 40 45]


1

In [9]:
arr2 = np.eye(5)
arr2.ndim

2

In [10]:
arr3 = np.array([[[1,2,3,4]],[[5,6,7,8]]])
arr3.ndim

3

# reshape()

In [11]:
arr1 = np.random.randint(1,50,12)
print(arr1, end="\n\n")
print(arr1.reshape(6,2), end="\n\n") # 6*2 = 12
print(arr1.reshape(4,3), end="\n\n") # 4*3 = 12

[13  6 29 28 14 31 45 15 35 21 23 15]

[[13  6]
 [29 28]
 [14 31]
 [45 15]
 [35 21]
 [23 15]]

[[13  6 29]
 [28 14 31]
 [45 15 35]
 [21 23 15]]



# flatten()

In [12]:
arr1 = np.eye(3)
print(arr1, end="\n\n")
print(arr1.flatten())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[1. 0. 0. 0. 1. 0. 0. 0. 1.]


In [13]:
arr2 = np.full((2,3),4)
print(arr2.flatten())

[4 4 4 4 4 4]


# concatenate()

In [14]:
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)
print(arr1)
print(arr2)
np.concatenate((arr1, arr2))

[1 2 3 4 5]
[ 6  7  8  9 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# split()

In [21]:
arr1 = np.arange(1,7)
np.split(arr1, 3)
"""np.split(arr1, 4) throws error. 
Splitted sections should be such that each array 
should have equal number of elements."""

[array([1, 2]), array([3, 4]), array([5, 6])]

# max() argmax() & min() and argmin()

In [32]:
arr1 = np.random.randint(1,50,20)
print(arr1,  end="\n\n")

print(f"Maximum number in the array = {arr1.max()}")
print(f"Index position of max num ({arr1.max()}) is {arr1.argmax()}")
print()
print(f"Minimum number in the array = {arr1.min()}")
print(f"Index position of min num ({arr1.min()}) is {arr1.argmin()}")

[48 27 21 28 45  1 29 19 20 43 31 28  8 24 14 44 18  4  5 48]

Maximum number in the array = 48
Index position of max num (48) is 0

Minimum number in the array = 1
Index position of min num (1) is 5


# sum() & mean()

In [35]:
arr1 = np.array([1, 2, 3, 4, 5]) # np.arange(1,6)
print(f"Sum = {arr1.sum()}") # 1+2+3+4+5 = 15
print(f"Mean = {arr1.mean()}") # sum/size = 15/5 = 3.0

Sum = 15
Mean = 3.0
