## Problem 1: Array Creation
1. Create a 1D NumPy array with values ranging from 1 to 10.
2. Create a 2D NumPy array filled with zeros of shape (3, 4).
3. Create a 2D array with random integers between 0 and 50 of shape (4, 5).


In [63]:
import numpy as np

print(np.arange(1, 11)) # Q.No.1

print(np.zeros((3,4))) # # Q.No.2

print(np.random.randint(0, 50,20).reshape(4,5)) # Q.No.3

[ 1  2  3  4  5  6  7  8  9 10]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[38  1  1 47 48]
 [46 48 25 14 23]
 [30 29 44 37 44]
 [36 20 30 17  2]]


## Problem 2
You are given the following array:
```python
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])
```
Your tasks are:
1. Retrieve the first 3 elements.
2. Retrieve the last 2 elements.
3. Retrieve every second element from the array.


In [68]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[:3])

print(arr[-2:])

print(arr[::2])

[10 20 30]
[60 70]
[10 30 50 70]


## Problem 3: Basic Array Operations
You are given the following arrays:
```python
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
```
Your tasks are:
1. Add the two arrays.
2. Multiply the two arrays element-wise.
3. Compute the dot product of the two arrays.


In [76]:
import numpy as np
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)

print(arr1+arr2)
print(arr1*arr2)
print(arr1.dot(arr2))

[ 6  8 10 12]
[ 5 12 21 32]
70


## Problem 4: Reshaping Arrays
You are given a 1D array:
```python
arr = np.arange(1, 13)  # Array with values from 1 to 12
```
Your tasks are:
1. Reshape the array into a 2D array of shape (3, 4).
2. Reshape the array into a 3D array of shape (2, 2, 3).


In [80]:
import numpy as np
arr = np.arange(1,13)
print(arr.reshape(3,4))
print(arr.reshape(2,2,3))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Problem 5: Statistical Functions
You are given the following array:
```python
data = np.array([10, 20, 30, 40, 50])
```
Your tasks are:
1. Compute the mean of the array.
2. Compute the sum of the array.
3. Find the maximum and minimum values in the array.


In [91]:
import numpy as np
data = (np.linspace(10,50,5)).astype('int32')
print(data)
print(f"Mean = {np.mean(data)}")
print(f"Sum = {np.sum(data)}")
print(f"Max = {np.max(data)}")
print(f"Min = {np.min(data)}")

[10 20 30 40 50]
Mean = 30.0
Sum = 150
Max = 50
Min = 10


## Problem 6: Boolean Masking
You are given the following array:
```python
arr = np.array([5, 15, 25, 35, 45, 55])
```
Your tasks are:
1. Create a boolean mask for values greater than 30.
2. Use the mask to extract the values greater than 30.


In [100]:
import numpy as np
arr = np.arange(5,56, 10)
print(arr)
mask = arr>30
print(mask) # boolean mask
print(arr[mask]) # extracting elements using boolean mask

[ 5 15 25 35 45 55]
[False False False  True  True  True]
[35 45 55]


## Problem 7: Broadcasting
You are given the following array:
```python
arr = np.array([10, 20, 30, 40])
```
Your tasks are:
1. Add 5 to each element of the array using broadcasting.
2. Multiply each element of the array by 2 using broadcasting.


import numpy as np
arr = np.arange(10,41,10)
print(arr)
print(arr+5)
print(arr*2)

## Problem 8: Matrix Operations
You are given the following 2D arrays:
```python
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
```
Your tasks are:
1. Compute the element-wise sum of the two matrices.
2. Compute the matrix product of `matrix1` and `matrix2`.


In [113]:
import numpy as np
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(matrix1 + matrix2)
print(np.matmul(matrix1, matrix2))

[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]



## Problem 9: Creating Special Arrays
1. Create an identity matrix of size 4x4.
2. Create a diagonal matrix with the diagonal values [10, 20, 30, 40].


In [117]:
import numpy as np

print(np.eye(4,4))

print(np.diag((np.linspace(10,40,4)).astype('int32')))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]



## Problem 10: Save and Load Arrays
1. Save the following array to a file using `np.save`:
    ```python
    arr = np.array([1, 2, 3, 4, 5])
    ```
2. Load the saved array back and print its contents.


In [122]:
import numpy as np
arr = np.arange(1,6)
np.save('test', arr)

In [124]:
data = np.load('test.npy')
print(data)

[1 2 3 4 5]
